export const handleError = err  => {
    console.log(err.message);
    process.exit(1)
}